services:
  - redis-server
addons:
  postgresql: "9.6"
language: clojure
lein: lein
before_script:
  - cp -f resources/config.travis.edn resources/config.test.edn
  - psql -c 'create database whosin_test;' -U postgres
  - ENVIRONMENT=test lein migrate
script:
  - lein do clean, test
jdk:
  - oraclejdk8
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
