version: "3"

services:
  db:
    image: postgres:9.6
    ports:
      - "15432:5432"
    volumes:
      - ./.dbdata://var/lib/postgresql/data
    environment:
      - POSTGRES_DB=whosin_dev
      - POSTGRES_USER=whosin
      - POSTGRES_PASSWORD=p@ssw0rd
