
CREATE TABLE W_ROLL_CALLS (
   ID SERIAL PRIMARY KEY,
   CHAT_ID BIGINT NOT NULL,
   STATUS VARCHAR(100) NOT NULL,
   TITLE TEXT NOT NULL,
   QUIET BOOLEAN NOT NULL DEFAULT FALSE,

   CREATED_AT TIMESTAMP NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL
);

CREATE INDEX IDX_W_ROLL_CALLS_CHAT_ID ON W_ROLL_CALLS(CHAT_ID)
