
CREATE TABLE W_ROLL_CALL_RESPONSES (
    ID SERIAL PRIMARY KEY,

    USER_ID BIGINT,
    USER_NAME TEXT,

    STATUS VARCHAR(100) NOT NULL,
    REASON TEXT,

    ROLL_CALL_ID BIGINT REFERENCES W_ROLL_CALLS(ID)
    ON DELETE CASCADE ON UPDATE CASCADE,

    UNIQUE_TOKEN VARCHAR(512),

    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    UNIQUE (ROLL_CALL_ID, UNIQUE_TOKEN)
);

CREATE INDEX IDX_W_ROLL_CALL_RESPONSES_ROLL_CALL_ID ON W_ROLL_CALL_RESPONSES(ROLL_CALL_ID);
